services:
  backend:
    image: yata-backend
    build:
      context: ./backend
    volumes:
      - yata-data:/app/data

  frontend:
    image: yata-frontend
    build:
      context: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  yata-data:
    